### ISSUE TITLE
get_include returns incorrect directory in pip isolated environments

### ISSUE THREAD

**Issue by auscompgeek** [pybind/pybind11#1644]
## Issue description

`pybind11.get_include()` does not work correctly in a pip isolated build environment (when installing a package that has a pyproject.toml - see PEP 518).

### pyproject.toml
```toml
[build-system]
requires = ["setuptools", "wheel", "pybind11>=2.2"]
```
