### ISSUE TITLE
[BUG]: Unexpected behavior for binding to a data member, which is returned-by-reference by a member function

### ISSUE THREAD

**Issue by hyliu1989** [pybind/pybind11#4858]
### Required prerequisites

- [X] Make sure you've read the [documentation](https://pybind11.readthedocs.io). Your issue may be addressed there.
- [X] Search the [issue tracker](https://github.com/pybind/pybind11/issues) and [Discussions](https:/pybind/pybind11/discussions) to verify that this hasn't already been reported. +1 or comment there if it has.
- [X] Consider asking first in the [Gitter chat room](https://gitter.im/pybind/Lobby) or in a [Discussion](https:/pybind/pybind11/discussions/new).

### What version (or hash if on master) of pybind11 are you using?

pybind11-2.11.1-py3-none-any.whl.metadata

### Problem description

The binding to a data member behaves differently when the data member is declared in Pybind11 and when it is not. In class `TestBind` there is a member function `Enclosed& get(int level)` that will return a reference to its data member. This `get` function is bound to Python. When calling this function twice in Python, assigning to two variables `enc` and `enc2`, I got `enc.c != enc2.c` which is unexpected because the two variables should refer to the same data member.

However, by adding a line`.def_readonly("enclosed", &TestBind::_enclosed)` in the definition of Pybind11-binding (currently commented out), I got `enc.c == enc2.c` result. This inconsistency made me think that this is a potential bug. Could someone please point me out which thing I have missed?

```cpp
#include <pybind11/pybind11.h>
namespace py = pybind11;

class Enclosed {
public:
    Enclosed() { c = 4; }
    int c;
};

class TestBind {
public:
    TestBind() : _enclosed() {
        _enclosed.c = 5;
    }
    int some_height{20};
    int a_factor{0};
    bool use_stripes{false};
    Enclosed& get(int level) { _enclosed.c += level; return _enclosed; };
    int get_a() { return a_factor; }
    Enclosed _enclosed;
};

PYBIND11_MODULE(_example, m) {
    m.doc() = R"pbdoc(Bug report)pbdoc";

    py::class_<Enclosed>(m, "Enclosed")
        .def(py::init<>())
        .def_readwrite("c", &Enclosed::c);

    py::class_<TestBind>(m, "TestBind")
        .def(py::init<>())
        .def_readwrite("some_height", &TestBind::some_height)
        .def_readwrite("a_factor", &TestBind::a_factor)
        .def_readwrite("use_stripes", &TestBind::use_stripes)
        // .def_readonly("enclosed", &TestBind::_enclosed)
        .def("get", &TestBind::get)
        .def("get_a", &TestBind::get_a);

    m.attr("__version__") = "dev";
}
```

Here is a short pytest code

```python
import myproj._example

def test_enclosed_class():
    a = myproj._example.TestBind()
    value_to_send = 3
    enc = a.get(value_to_send)
    assert enc.c == 5 + value_to_send

    value_to_send_2 = 7
    enc2 = a.get(value_to_send_2)
    assert enc2.c == 5 + value_to_send + value_to_send_2
    assert enc.c == 5 + value_to_send + value_to_send_2
```

The building related files are listed below

pyproject.toml
```toml
[build-system]
requires = ["scikit-build-core>=0.5.0", "pybind11", "numpy"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
wheel.expand-macos-universal-tags = true

[project]
name = "myproj"
version = "0.1.0"
description="MYPROJ"
authors = [{ name = "My Name", email = "me@email.com" }]
requires-python = ">=3.10"
classifiers = [
  "Development Status :: 3 - Alpha",
  # "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  # "Operating System :: OS Independent",
]
urls = { Homepage = "https://nodarsensor.com" }
dependencies = [  # related to "requires" in setup.py.  See https://peps.python.org/pep-0621/#other-names-for-dependencies-optional-dependencies

]

# Originally called "extra-requires" but the python community decided to rename it.
# https://peps.python.org/pep-0621/#other-names-for-dependencies-optional-dependencies
[project.optional-dependencies]
dev = [
  "black",
  "isort",
  "mypy",
  "pre-commit",
  "pytest",
  "pybind11",
  "ipython >= 8.15.0",
  "jupyter >= 1.0.0",
  "notebook >= 7.0.3",
]
all = [
  "myproj[dev]",
]
```

CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.15...3.26)

# Setup the cmake environment
# dependencies required for python binding.
find_package(Python REQUIRED COMPONENTS Interpreter Development.Module)
find_package(pybind11 CONFIG REQUIRED)


# Python project definition.
project(
  ${SKBUILD_PROJECT_NAME}
  VERSION ${SKBUILD_PROJECT_VERSION}
  LANGUAGES CXX
)


# Build a Python-readable cpp module.
## compile the python-readable cpp module.
set(PYTHON_MODULE_NAME _example)
python_add_library(${PYTHON_MODULE_NAME} MODULE cpp_src/example.cpp WITH_SOABI)
target_link_libraries(
    ${PYTHON_MODULE_NAME}
    PRIVATE
    pybind11::headers
)
target_compile_definitions(
    ${PYTHON_MODULE_NAME}
    PRIVATE
    VERSION_INFO=${PROJECT_VERSION}
)
## install the python-readable wrapper module
install(
    TARGETS ${PYTHON_MODULE_NAME} 
    DESTINATION ${SKBUILD_PROJECT_NAME}
)
```

### Reproducible example code

```text
#include <pybind11/pybind11.h>
namespace py = pybind11;

class Enclosed {
public:
    Enclosed() { c = 4; }
    int c;
};

class TestBind {
public:
    TestBind() : _enclosed() {
        _enclosed.c = 5;
    }
    int some_height{20};
    int a_factor{0};
    bool use_stripes{false};
    Enclosed& get(int level) { _enclosed.c += level; return _enclosed; };
    int get_a() { return a_factor; }
    Enclosed _enclosed;
};

PYBIND11_MODULE(_example, m) {
    m.doc() = R"pbdoc(Bug report)pbdoc";

    py::class_<Enclosed>(m, "Enclosed")
        .def(py::init<>())
        .def_readwrite("c", &Enclosed::c);

    py::class_<TestBind>(m, "TestBind")
        .def(py::init<>())
        .def_readwrite("some_height", &TestBind::some_height)
        .def_readwrite("a_factor", &TestBind::a_factor)
        .def_readwrite("use_stripes", &TestBind::use_stripes)
        // .def_readonly("enclosed", &TestBind::_enclosed)
        .def("get", &TestBind::get)
        .def("get_a", &TestBind::get_a);

    m.attr("__version__") = "dev";
}
```

### Is this a regression? Put the last known working version here if it is.

Not a regression
